Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox" do |vb|
        vb.name = "wordpress"
        vb.memory = 2048
      end

    config.vm.box = "bento/amazonlinux-2"
    config.vm.network "private_network", ip: "192.168.33.11"
    config.vm.network "forwarded_port", guest: 80, host: 8080

    config.vm.synced_folder "../_work", "/home/vagrant/_work"
    config.vm.synced_folder "../ansible", "/home/vagrant/ansible", mount_options: ["dmode=775,fmode=664"]

    config.vbguest.auto_update= false
    config.vm.provision :shell, :path => "bootstrap.sh"
  end
